apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= name %>
  namespace: <%= project.namespace %>
  labels:
    caninemanaged: 'true'
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-pass-headers: "*"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    <% ingress_endpoint.domains.each do |domain| %>
    - <%= domain.domain_name %>
    <% end %>
    secretName: <%= certificate_name %>
  rules:
  <% ingress_endpoint.domains.each do |domain| %>
  - host: <%= domain.domain_name %>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <%= ingress_endpoint.endpoint_name %>
            port:
              number: <%= ingress_endpoint.port %>
  <% end %>