apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: <%= gateway_name %>
  namespace: <%= add_on.name %>
  labels:
    caninemanaged: 'true'
spec:
  gatewayClassName: traefik
  listeners:
  <% domains.each do |domain| %>
  - name: <%= domain.gsub(/[^a-z0-9]/i, '-').downcase %>
    protocol: HTTPS
    port: 443
    hostname: <%= domain %>
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: <%= certificate_name %>
    allowedRoutes:
      namespaces:
        from: Same
  <% end %>
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: <%= route_name %>
  namespace: <%= add_on.name %>
  labels:
    caninemanaged: 'true'
spec:
  parentRefs:
  - name: <%= gateway_name %>
  hostnames:
  <% domains.each do |domain| %>
  - <%= domain %>
  <% end %>
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: <%= endpoint.metadata.name %>
      port: <%= port %>
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <%= endpoint.metadata.name %>-certificate
  namespace: <%= add_on.name %>
  labels:
    caninemanaged: 'true'
spec:
  secretName: <%= certificate_name %>
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  <% domains.each do |domain| %>
  - <%= domain %>
  <% end %>
