apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= endpoint_name %>
  namespace: <%= add_on.name %>
  labels:
    caninemanaged: 'true'
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    <% domains.each do |domain| %>
    - <%= domain.domain_name %>
    <% end %>
    secretName: <%= endpoint_name %>-tls
  rules:
  <% domains.each do |domain| %>
  - host: <%= domain.domain_name %>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <%= endpoint_name %>
            port:
              number: <%= port %>
  <% end %>